name: FileDrap
options:
  minimumXcodeGenVersion: 2.43.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.qian.filedrap
    MACOSX_DEPLOYMENT_TARGET: 13.0
    SWIFT_VERSION: 6.0
    DEVELOPMENT_TEAM: ""
targets:
  FileDrap:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_NAME: FileDrap
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_CFBundleName: FileDrap
        INFOPLIST_KEY_CFBundleDisplayName: FileDrap
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Sources/FileDrap/FileDrap.entitlements
    scheme:
      testTargets:
        - FileDrapTests
  FileDrapTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: FileDrap
